# Generated by Django 5.2.7 on 2025-11-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Entrada')),
                ('queixa', models.TextField(verbose_name='Queixa Principal')),
                ('status', models.CharField(choices=[('TRIAGEM', 'Triagem'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_EXAME', 'Aguardando Exame'), ('EM_EXAME', 'Em Exame'), ('AGUARDANDO_RESULTADO', 'Aguardando Resultado'), ('ALTA', 'Alta'), ('INTERNACAO', 'Internação')], default='TRIAGEM', max_length=30, verbose_name='Status')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='pacientes.paciente', verbose_name='Paciente')),
                ('profissional_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='usuarios.profissional', verbose_name='Profissional Responsável')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_hora_entrada'],
            },
        ),
    ]
