# Generated by Django 5.2.7 on 2025-11-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANAMNESE', 'Anamnese'), ('EVOLUCAO_MEDICA', 'Evolução Médica'), ('EVOLUCAO_ENFERMAGEM', 'Evolução de Enfermagem'), ('EXAME_FISICO', 'Exame Físico')], max_length=30, verbose_name='Tipo de Evolução')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes', to='atendimentos.atendimento', verbose_name='Atendimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes', to='usuarios.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Evolução Clínica',
                'verbose_name_plural': 'Evoluções Clínicas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
