# Generated by Django 5.2.7 on 2025-11-15 02:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('prontuario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinalVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial_sistolica', models.PositiveSmallIntegerField(blank=True, help_text='Valor entre 50 e 300 mmHg', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)], verbose_name='Pressão Arterial Sistólica (mmHg)')),
                ('pressao_arterial_diastolica', models.PositiveSmallIntegerField(blank=True, help_text='Valor entre 30 e 200 mmHg', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Pressão Arterial Diastólica (mmHg)')),
                ('frequencia_cardiaca', models.PositiveSmallIntegerField(blank=True, help_text='Valor entre 30 e 250 bpm', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Frequência Cardíaca (bpm)')),
                ('frequencia_respiratoria', models.PositiveSmallIntegerField(blank=True, help_text='Valor entre 8 e 60 irpm', null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(60)], verbose_name='Frequência Respiratória (irpm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Valor entre 32.0 e 45.0 °C', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(32.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Temperatura (°C)')),
                ('saturacao_o2', models.PositiveSmallIntegerField(blank=True, help_text='Valor entre 50 e 100%', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Saturação de O₂ (%)')),
                ('glicemia', models.PositiveSmallIntegerField(blank=True, help_text='Valor entre 20 e 600 mg/dL', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)], verbose_name='Glicemia (mg/dL)')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre a aferição', verbose_name='Observações')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinais_vitais', to='atendimentos.atendimento', verbose_name='Atendimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinais_vitais_registrados', to='usuarios.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Sinal Vital',
                'verbose_name_plural': 'Sinais Vitais',
                'ordering': ['-data_hora'],
            },
        ),
    ]
