# Generated by Django 5.2.7 on 2025-11-15 05:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('prontuario', '0002_sinalvital'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Prescrição')),
                ('validade', models.DateField(help_text='Data até quando a prescrição é válida', verbose_name='Validade')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('SUSPENSA', 'Suspensa'), ('CONCLUIDA', 'Concluída')], default='ATIVA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a prescrição (opcional)', verbose_name='Observações Gerais')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='atendimentos.atendimento', verbose_name='Atendimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_realizadas', to='usuarios.profissional', verbose_name='Médico Responsável')),
            ],
            options={
                'verbose_name': 'Prescrição Médica',
                'verbose_name_plural': 'Prescrições Médicas',
                'ordering': ['-data_prescricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(help_text='Nome do medicamento', max_length=200, verbose_name='Medicamento')),
                ('dose', models.CharField(help_text='Ex: 500mg, 10ml, 2 comprimidos', max_length=100, verbose_name='Dose')),
                ('via', models.CharField(choices=[('ORAL', 'Oral'), ('INTRAVENOSA', 'Intravenosa (IV)'), ('INTRAMUSCULAR', 'Intramuscular (IM)'), ('SUBCUTANEA', 'Subcutânea (SC)'), ('TOPICA', 'Tópica'), ('INALATORIA', 'Inalatória'), ('SUBLINGUAL', 'Sublingual'), ('RETAL', 'Retal'), ('OCULAR', 'Ocular'), ('NASAL', 'Nasal')], max_length=20, verbose_name='Via de Administração')),
                ('frequencia', models.CharField(help_text='Ex: 8/8h, 12/12h, 1x ao dia', max_length=100, verbose_name='Frequência')),
                ('duracao_dias', models.PositiveSmallIntegerField(help_text='Quantidade de dias do tratamento', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Duração (dias)')),
                ('observacoes_item', models.TextField(blank=True, help_text='Instruções específicas para este medicamento (opcional)', verbose_name='Observações do Item')),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='prontuario.prescricao', verbose_name='Prescrição')),
            ],
            options={
                'verbose_name': 'Item da Prescrição',
                'verbose_name_plural': 'Itens da Prescrição',
                'ordering': ['id'],
            },
        ),
    ]
