# Generated by Django 5.2.7 on 2025-11-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('prontuario', '0003_prescricao_itemprescricao'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LABORATORIO', 'Laboratório'), ('IMAGEM', 'Imagem'), ('CARDIOLOGIA', 'Cardiologia'), ('ANATOMIA_PATOLOGICA', 'Anatomia Patológica'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo de Exame')),
                ('nome_exame', models.CharField(help_text='Ex: Hemograma completo, Raio-X de tórax, Eletrocardiograma', max_length=200, verbose_name='Nome do Exame')),
                ('justificativa', models.TextField(help_text='Motivo da solicitação do exame', verbose_name='Justificativa Clínica')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('COLETADO', 'Coletado'), ('RESULTADO_DISPONIVEL', 'Resultado Disponível'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=30, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_exame', to='atendimentos.atendimento', verbose_name='Atendimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames_solicitados', to='usuarios.profissional', verbose_name='Médico Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Exame',
                'verbose_name_plural': 'Solicitações de Exames',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_texto', models.TextField(help_text='Descrição textual do resultado do exame', verbose_name='Resultado')),
                ('arquivo_laudo', models.FileField(blank=True, help_text='Upload do laudo em PDF ou imagem (opcional)', null=True, upload_to='laudos/%Y/%m/', verbose_name='Arquivo do Laudo')),
                ('data_resultado', models.DateTimeField(auto_now_add=True, verbose_name='Data do Resultado')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o resultado (opcional)', verbose_name='Observações')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultado', to='prontuario.solicitacaoexame', verbose_name='Solicitação de Exame')),
            ],
            options={
                'verbose_name': 'Resultado de Exame',
                'verbose_name_plural': 'Resultados de Exames',
                'ordering': ['-data_resultado'],
            },
        ),
    ]
