# Generated by Django 5.2.7 on 2025-11-07 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Paciente',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                        ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter exatamente 11 dígitos numéricos', regex='^\\d{11}$')], verbose_name='CPF')),
                        ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                        ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo')),
                        ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe')),
                        ('telefone', models.CharField(blank=True, help_text='Somente números (DDD + número)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos (incluindo DDD)', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                        ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                        ('cartao_sus', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Cartão SUS deve conter exatamente 15 dígitos', regex='^\\d{15}$')], verbose_name='Cartão SUS')),
                        ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                        ('cep', models.CharField(blank=True, help_text='Somente números', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 dígitos', regex='^\\d{8}$')], verbose_name='CEP')),
                        ('rua', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua/Avenida')),
                        ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                        ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                        ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                        ('uf', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='UF deve conter exatamente 2 letras maiúsculas', regex='^[A-Z]{2}$')], verbose_name='UF')),
                        ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                        ('alergias', models.TextField(blank=True, help_text='Liste medicamentos, alimentos ou outras substâncias', null=True, verbose_name='Alergias')),
                        ('observacoes_clinicas', models.TextField(blank=True, help_text='Doenças pré-existentes, cirurgias anteriores, etc.', null=True, verbose_name='Observações Clínicas')),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('atualizado_em', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Paciente',
                        'verbose_name_plural': 'Pacientes',
                        'ordering': ['nome'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE atendimento_paciente RENAME TO pacientes_paciente;',
                    reverse_sql='ALTER TABLE pacientes_paciente RENAME TO atendimento_paciente;',
                ),
            ],
        ),
    ]
