# Generated by Django 5.2.7 on 2025-11-07 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMEIRO', 'Enfermeiro'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20, verbose_name='Perfil de Acesso')),
                ('registro_profissional', models.CharField(blank=True, help_text='CRM, COREN ou outro registro', max_length=50, null=True, verbose_name='Registro Profissional')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
