# Generated by Django 5.0.1 on 2025-10-21 02:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter exatamente 11 dígitos numéricos', regex='^\\d{11}$')], verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Entrada')),
                ('queixa', models.TextField(verbose_name='Queixa Principal')),
                ('status', models.CharField(choices=[('TRIAGEM', 'Triagem'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_EXAME', 'Aguardando Exame'), ('EM_EXAME', 'Em Exame'), ('AGUARDANDO_RESULTADO', 'Aguardando Resultado'), ('ALTA', 'Alta'), ('INTERNACAO', 'Internação')], default='TRIAGEM', max_length=30, verbose_name='Status')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimento.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_hora_entrada'],
            },
        ),
    ]
