# Generated by Django 5.2.7 on 2025-11-06 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_profissional_atendimento_profissional_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Liste medicamentos, alimentos ou outras substâncias', null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cartao_sus',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Cartão SUS deve conter exatamente 15 dígitos', regex='^\\d{15}$')], verbose_name='Cartão SUS'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, help_text='Somente números', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 dígitos', regex='^\\d{8}$')], verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacoes_clinicas',
            field=models.TextField(blank=True, help_text='Doenças pré-existentes, cirurgias anteriores, etc.', null=True, verbose_name='Observações Clínicas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua/Avenida'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Somente números (DDD + número)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos (incluindo DDD)', regex='^\\d{10,11}$')], verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='UF deve conter exatamente 2 letras maiúsculas', regex='^[A-Z]{2}$')], verbose_name='UF'),
        ),
    ]
